  tendabeli2mqtt:
    container_name: tendabeli2mqtt
    image: tendabeli2mqtt:latest
    environment:
    - MQTT_HOST=10.0.0.2
    - MQTT_PORT=1883
    - MQTT_USER=user
    - MQTT_PASSWORD=password
    - MQTT_QOS=1
    - BASE_TOPIC=tendabeli2mqtt
    - DEVICE_IPS=10.0.1.4,10.0.1.20
    - LOG_LEVEL=debug
    restart: unless-stopped